FROM quay.io/centos/centos:stream

RUN true \
 && dnf -y install python3-pip \
 && pip3 install jenkins-job-builder \
 && pip3 install dataclasses \
 && dnf -y clean all \
 && true

COPY . /opt/build/

# make jobs directory writable, otherwise deploy-centos-ci.sh fails
RUN chmod ugo=rwx /opt/build/jobs

WORKDIR /opt/build

CMD ["sh", "-c", "tests/verify-yaml.sh"]
