- hosts: gluster_nodes[0]
  tasks:
  - name: Create a folder for each server
    file:
      state: directory
      path: "/root/gluster-logs/{{ hostvars[item]['hostname'] }}-{{ hostvars[item]['ansible_host'] }}"
    with_items: "{{ groups['gluster_nodes'][1:] }}"

- hosts: gluster_nodes[1:]
  tasks:
  - name: Copy gluster logs
    synchronize:
      src: /var/log/glusterfs
      dest: "/root/gluster-logs/{{ ansible_hostname }}-{{ ansible_eth0.ipv4.address }}"
    delegate_to: "{{ groups['gluster_nodes'][0] }}"

  - name: Copy samba logs
    synchronize:
      src: /var/log/samba
      dest: "/root/gluster-logs/{{ ansible_hostname }}-{{ ansible_eth0.ipv4.address }}"
    delegate_to: "{{ groups['gluster_nodes'][0] }}"

- hosts: gluster_nodes[0]
  tasks:
  - name: Archive the directory
    archive:
      path: "/root/gluster-logs"
      format: gz
      dest: "/root/gluster-logs.gz"
